### ISSUE TITLE
Verzamelissue missende definities

### ISSUE THREAD

**Issue by pmaria** [Geonovum/disgeo-begrippen#4]
In dit issue verzamelen missende definities voor begrippen.

**Comment by gabswiersma** [comment]
Voor begrippen die onderdeel uitmaken van / nodig zijn voor het definiëren van het domein Water:

**Water (fysiek)**
* [Watervlakte subtypes](https://geonovum.github.io/disgeo-inhoud-2/#watervlakte):
   - Meer
   - Plas
   - Ven
   - Vijver

**Water (functioneel)**
* [Complex](https://geonovum.github.io/disgeo-inhoud-2/#complex)
* [Complex subtypes](https://geonovum.github.io/disgeo-inhoud-2/#complex):
   - Havencomplex
   - Gemaalcomplex
   - Sluiscomplex
   - Stuwcomplex
   - Coupurecomplex

**Kunstwerk**
* [Ondertunneling](https://geonovum.github.io/disgeo-inhoud-2/#ondertunneling)
* [Sluisdelen](https://geonovum.github.io/disgeo-inhoud-2/#sluisdeel):
   - Sluisdeur
   - Kolk
